[package]
name = "email_gen"
version = "0.1.0"
authors = ["Vadim <vadillamc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_regex = "0.15.1"
rand="0.8.3"
rand_xorshift="0.3.0"